Add files via upload
todor-shishmanoff/myappsample pull request #2
Opened 2021-01-25 14:33 UTC by todor-shishmanoff

2021-01-26 11:32 UTC, MariyaShishmanova commented on myindexCats.html
> +            <section class="section section-gallery section-gallery--size-1">
section-gallery--size-1 е излишно според мен

2021-01-26 11:32 UTC, MariyaShishmanova commented on myindexCats.html
> +                        <div class="section-gallery--size-1__head">
това според мен е section-gallery__head и вътре в него - някакво h, не мисля че тр да е а, ама може и а да е

2021-01-26 11:32 UTC, MariyaShishmanova commented on myindexCats.html
> +                        <div class="section-gallery--size-1__media">
section-gallery--size-1__media мисля че трябва да е section-gallery__body. 
вътре в него да имаш ul.gallery > li.gallery__item.gallery__item--1of2 >img .

2021-01-26 11:32 UTC, MariyaShishmanova commented on myindexCats.html
> +                                    <div class="img">
div.img е излишно. щом имаш li - li държи инлайн елементаи няма смисъл от div. Ako imashe i други елементи в li, тогава вече ще тр див който да рапва имг

2021-01-26 11:32 UTC, MariyaShishmanova commented on myindexCats.html
> +            <section class="section section-gallery section-gallery--size-2">
тази може да се казва section.section.section-list-articles

2021-01-26 11:32 UTC, MariyaShishmanova commented on myindexCats.html
> +                    <div class="section-gallery--size-2__articles">
tova da e section__inner

2021-01-26 11:32 UTC, MariyaShishmanova commented on myindexCats.html
> +                        <ul>
ul da e  ul.articles.columns

2021-01-26 11:32 UTC, MariyaShishmanova commented on myindexCats.html
> +                            <li class="article">
li.article.column

2021-01-26 11:32 UTC, MariyaShishmanova commented on myindexCats.html
> +                            <li class="article">
i v li da imash article.article

2021-01-26 11:32 UTC, MariyaShishmanova commented on myindexCats.html
> +                                    <h4 class="article__title">500 Internal Server Error</h4>
h4 moje da e v div,article__head

2021-01-26 11:32 UTC, MariyaShishmanova commented on myindexCats.html
> +                                    <div class="article__content-text">
a tova da e article__entry

2021-02-10 09:07 UTC, georgigrigorov commented on cats/myindexCats2.html
> +                            <h4>Gallery</h4>
Бих ползвал h2 с клас section-gallery__title

2021-02-10 09:07 UTC, georgigrigorov commented on cats/myindexCats2.html
> +                                <li class="gallery__item gallery__item--1of2">
super

2021-02-10 09:07 UTC, georgigrigorov commented on cats/myindexCats2.html
> +                            <a href="#">HTTPS://HTTP CAT/[STATUS_CODE]</a>
Това не е линк, а по скоро е `code`

2021-02-10 09:09 UTC, georgigrigorov commented on cats/myindexCats2.html
> +                <div class="container container--md">
Мисля, че container класа ти е излишен или по скоро стиловете за него. Остави container, но стиловете от --md да отидат на container. Защото в момента май го ползваш само във футъра и хеадъра, а те реално не са по широки?

2021-02-10 09:10 UTC, georgigrigorov commented on cats/myindexCats2.html
> +                                        <h4 class="article__title">500 Internal Server Error</h4>
За тези бих заложил на h3

2021-02-10 09:11 UTC, georgigrigorov commented on cats/myindexCats2.html
> +                    <p>See more HTTPS cats here - <a href="#"> https://http.cat/.</a></p>
Трябва Https:// да го добавиш  и като href имаш един интервал в повече в самият линк

2021-02-10 09:11 UTC, georgigrigorov commented on cats/mystylesCats2.css
> +@import url("https://fonts.googleapis.com/css2?family=Abril+Fatface&family=Roboto:ital,wght@0,300;0,400;0,500;0,700;1,100;1,300&display=swap");
не ми харесва името на .css файла ти mystylesCats2.css

Той трябва да е styles.css
HTML -> index.html

2021-02-10 09:12 UTC, georgigrigorov commented on cats/mystylesCats2.css
> +  background-image: url(./images/145573.jpg);
Ако зуум аутнеш browser-a ще видиш какви проблеми има background-a. Не трябва да е така

2021-02-10 09:13 UTC, georgigrigorov commented on cats/mystylesCats2.css
> +.header__body h1 {
Тъй като на страница е позволено да има само 1 h1 таг, тук може направо да му сложиш клас page-title и да го стилнеш така... Но не е задължително :)

2021-02-10 09:13 UTC, georgigrigorov commented on cats/mystylesCats2.css
> +  color: lightgrey;
желателно е да използваш hex стойности вместо имената на цветовете

2021-02-10 09:13 UTC, georgigrigorov commented on cats/mystylesCats2.css
> +  background: rgb(45, 46, 46);
ако нямаш alpha, по-добре напиши hex

2021-02-10 09:14 UTC, georgigrigorov commented on cats/mystylesCats2.css
> +.section-gallery__head h4::after {
харесва ми ефекта, но имай в предвид, че такива неща се добавят само на интерактивни елементи.

2021-02-10 09:15 UTC, georgigrigorov commented on cats/mystylesCats2.css
> +  transition: width 0.3s ease 0s, left 0.3s ease 0s;
няма нужда да слагаш delay 0, той е по default толкова

2021-02-10 09:16 UTC, georgigrigorov commented on cats/mystylesCats2.css
> +  text-align: start;
Избягвай използването на експериментални properties https://developer.mozilla.org/en-US/docs/Web/CSS/text-align

2021-02-10 09:17 UTC, georgigrigorov commented on cats/mystylesCats2.css
> +  text-align: end;
отново Experimental property

2021-02-10 09:17 UTC, georgigrigorov commented on cats/mystylesCats2.css
> +  background: rgb(56, 56, 56);
hex

2021-02-10 09:18 UTC, georgigrigorov commented on cats/mystylesCats2.css
> +  height: 100%;
Проблем

![image](https://user-images.githubusercontent.com/7802953/107489734-a48bfe00-6b91-11eb-86ac-f05e4d9fb811.png)

2021-02-10 09:18 UTC, georgigrigorov commented on cats/mystylesCats2.css
> +  height: 100%;
Проблем 2 
![image](https://user-images.githubusercontent.com/7802953/107489781-b53c7400-6b91-11eb-990f-e1367122c515.png)

2021-02-10 09:19 UTC, georgigrigorov commented on cats/mystylesCats2.css
> +.footer {
много е голям шрифта на мобилно 
![image](https://user-images.githubusercontent.com/7802953/107489828-c4bbbd00-6b91-11eb-8273-94d8add9f09e.png)

2021-02-10 09:19 UTC, georgigrigorov commented on cats/myindexCats2.html
> +<!DOCTYPE html>
Трябва да оправиш респонсива още. Сайта ти трябва да изглежда добре поне до 360px na display-a 
![image](https://user-images.githubusercontent.com/7802953/107489916-de5d0480-6b91-11eb-91f2-c30e5a64c79b.png)

2021-02-10 09:20 UTC, georgigrigorov requested changes
Направи фиксовете

2021-02-11 15:24 UTC, georgigrigorov commented on cats/index.html
> +                                    <img src="./src/images/500.jpg" alt="">
Тези още се мачкат. Но респонсива вече е по-добре
![image](https://user-images.githubusercontent.com/7802953/107657550-ef8b3b80-6c8d-11eb-9eb7-8227bda177f0.png)

2021-02-11 15:26 UTC, georgigrigorov approved these changes
Така вече е добре, само снимките ище са проблемни

2021-02-11 15:26 UTC, merged